---
# tasks file for rke

- name: Install docker-ce (el OS family)
  include_tasks: node-configurations.yaml
  when: cluster_configuration_level == "base"
  

- name: Create the Cluster
  include_tasks: rke-up.yaml
  when: cluster_configuration_level == "up"